name: Run collection certification checks

permissions:
  contents: read

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

concurrency:
  group: cert-ver-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  call:
    uses: ansible-collections/partner-certification-checker/.github/workflows/certification-reusable.yml@v1.2.0 # zizmor: ignore[unpinned-uses]
    # Our collection requires ansible.netcommon >= 5.0.0 (ansible-core >= 2.14)
    # with:
    #   ansible-core-version: '2.17.0'
    #   automation-hub: true
    # secrets:
    #   AH_TOKEN: ${{ secrets.AH_TOKEN }}
