---
name: Partner Certification Check
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  certify:
    name: Certification Check
    runs-on: ubuntu-latest
    steps:
      - name: Perform Collection Certification
        uses: ansible-collections/partner-certification-checker@v1
        with:
          namespace: lantronix
          collection_name: oob
