name: Ansible Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: ansible_collections/lantronix/oob
      - uses: actions/setup-python@v7
        with:
          python-version: "3.12"
      - run: pip install ansible-lint
      - run: cd ansible_collections/lantronix/oob && ansible-lint
